### PR TITLE
fix: compare when name is the same but not variant

### PR DESCRIPTION
**Pull request by Snowbaha**
When the name, price and tax are the same whereas the variant is not the same, it's merged. The fix compare the variant to be sure.

### CODE REVIEW

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
@Snowbaha thank you for your contribution, can you rebase the PR with master and fix the build by adjusting failing PHPSpec to your changes?

**Comment by Snowbaha** [comment]
I am not the more confident with PHPSpec :(

**Comment by GSadee** [comment]
You need to adjust this spec: https://github.com/Sylius/InvoicingPlugin/blob/master/spec/Entity/LineItemSpec.php#L94:L108 to use there a variant code that you've added to LineItem compare method, I encourage you to try 😃

**Comment by Snowbaha** [comment]
I tried, tell me if it is ok?

**Comment by Snowbaha** [comment]
it shoudl be ok! :)

**Review by GSadee — APPROVED** [review]

**Comment by GSadee** [comment]
Thank you, Julien! :tada:

**Pull request merged**
